-- Seed data for sliders table (Original Content)
INSERT INTO sliders (id, title, tag, description, highlight, image, brand, price, active, "order", specs, technical_specs, accent, color)
VALUES
(
  '1478f0ed-d71d-4b86-bd65-75a348467e59',
  'MacBook Pro 16',
  'New Release',
  'Experience uncompromised performance with the M3 Max chip. Designed for creators who demand the absolute best.',
  'M3 Max Powerhouse',
  '/images/macbook-pro-16.png',
  'Apple',
  249900,
  true,
  1,
  '[{"icon": "Cpu", "label": "M3 Max", "value": "16-Core"}, {"icon": "Zap", "label": "Memory", "value": "128GB"}, {"icon": "Battery", "label": "Battery", "value": "22 Hrs"}]'::jsonb,
  '{"cpu": "M3 Max", "ram": "128GB", "screen": "16-inch Liquid Retina XDR", "storage": "2TB SSD"}'::jsonb,
  'bg-blue-500',
  'from-blue-500/20 to-purple-500/20'
),
(
  '12c8fe1a-7d19-40f1-893e-f527cfcd606c',
  'Dell XPS 15',
  'Best Seller',
  'Immersive 3.5K OLED display in a stunningly crafted chassis. The perfect balance of power and portability.',
  'InfinityEdge Display',
  '/images/dell-xps-15.png',
  'Dell',
  189900,
  true,
  2,
  '[{"icon": "Star", "label": "Display", "value": "3.5K OLED"}, {"icon": "Cpu", "label": "Intel", "value": "i9-13900H"}, {"icon": "Zap", "label": "Graphics", "value": "RTX 4070"}]'::jsonb,
  '{"cpu": "Intel Core i9-13900H", "ram": "32GB", "screen": "15.6-inch 3.5K OLED", "storage": "1TB SSD"}'::jsonb,
  'bg-green-500',
  'from-green-500/20 to-emerald-500/20'
),
(
  '7182e7dc-00e0-452c-8fa2-8173d457d364',
  'ROG Zephyrus G14',
  'Gaming Beast',
  'Dominate the competition with the world''s most powerful 14-inch gaming laptop. Anime Matrix LED display included.',
  'Ultra-Portable Gaming',
  '/images/rog-zephyrus-g14.png',
  'Asus',
  149900,
  true,
  3,
  '[{"icon": "Zap", "label": "Refresh", "value": "165Hz"}, {"icon": "Cpu", "label": "Ryzen", "value": "9 7940HS"}, {"icon": "Shield", "label": "Cooling", "value": "Vapor"}]'::jsonb,
  '{"cpu": "AMD Ryzen 9 7940HS", "ram": "16GB", "screen": "14-inch QHD+ 165Hz", "storage": "1TB SSD"}'::jsonb,
  'bg-red-500',
  'from-red-500/20 to-orange-500/20'
),
(
  'da614d62-ccfd-492d-9393-9c063268397b',
  'ThinkPad X1 Carbon',
  'Business Pro',
  'Ultralight, ultrathin, and ultra-tough. The gold standard for business computing with military-grade durability.',
  'Legendary Reliability',
  '/images/thinkpad-x1.png',
  'Lenovo',
  169900,
  true,
  4,
  '[{"icon": "Shield", "label": "Build", "value": "Carbon"}, {"icon": "Battery", "label": "Weight", "value": "1.12kg"}, {"icon": "Laptop", "label": "Keyboard", "value": "Premium"}]'::jsonb,
  '{"cpu": "Intel Core i7-1365U", "ram": "16GB", "screen": "14-inch WUXGA", "storage": "512GB SSD"}'::jsonb,
  'bg-gray-500',
  'from-gray-500/20 to-slate-500/20'
),
(
  'ada36ca6-d9b2-4eba-96b1-542b554c9b87',
  'Surface Laptop Studio',
  'Creator''s Choice',
  'Seamlessly transition from laptop to studio mode. The ultimate canvas for digital artists and designers.',
  'Transform Your Workflow',
  '/images/surface-laptop-studio.png',
  'Microsoft',
  209900,
  true,
  5,
  '[{"icon": "Star", "label": "Screen", "value": "Touch"}, {"icon": "Cpu", "label": "Mode", "value": "3-in-1"}, {"icon": "Zap", "label": "Pen", "value": "Haptic"}]'::jsonb,
  '{"cpu": "Intel Core i7-11370H", "ram": "32GB", "screen": "14.4-inch PixelSense Flow", "storage": "1TB SSD"}'::jsonb,
  'bg-indigo-500',
  'from-indigo-500/20 to-pink-500/20'
)
ON CONFLICT (id) DO NOTHING;
